# Working with the columns

In [34]:
import pandas as pd
data = {
    'First':['convey','John','Jane'],
    'Last':['schafer','Doe','Doe'],
    'email':['corveyscafer@gmail.com','Johndoe@gmail.com','Janedoe@gmail.com']
}
df = pd.DataFrame(data)         # --> creating our own Dataframe
display(df)

    First     Last                   email
0  convey  schafer  corveyscafer@gmail.com
1    John      Doe       Johndoe@gmail.com
2    Jane      Doe       Janedoe@gmail.com

In [35]:
df["Full_name"] = df['First'] + ' ' + df['Last']  # --> creating the new column
display(df)

    First     Last                   email       Full_name
0  convey  schafer  corveyscafer@gmail.com  convey schafer
1    John      Doe       Johndoe@gmail.com        John Doe
2    Jane      Doe       Janedoe@gmail.com        Jane Doe

In [36]:
df.drop(columns=['First','Last']) # -->  deleting the column First and Last

                    email       Full_name
0  corveyscafer@gmail.com  convey schafer
1       Johndoe@gmail.com        John Doe
2       Janedoe@gmail.com        Jane Doe

In [37]:
df['Full_name'].str.split(' ',expand=True) # --> spliting on the basis of the space given in inverted comma

        0        1
0  convey  schafer
1    John      Doe
2    Jane      Doe

# Working on the rows

In [38]:
df.loc[len(df)] = ['Owais','Shk','owais123@gmail.com', 'Owais Shk' ] # --> To add new row 
display(df)

    First     Last                   email       Full_name
0  convey  schafer  corveyscafer@gmail.com  convey schafer
1    John      Doe       Johndoe@gmail.com        John Doe
2    Jane      Doe       Janedoe@gmail.com        Jane Doe
3   Owais      Shk      owais123@gmail.com       Owais Shk

In [39]:
df2 = {
    'First' : ['Tony','Steve'],
    'Last' : ['Stark','Rogers'],
    'email' : ['Ironman@gmail.com','CaptainAmerica@gmail.com'],
    'Full_name' : ['Tony Stark' , 'Steve Rogers']
}
df2 = pd.DataFrame(df2) # --> making dataframe df2
display(df2)

   First    Last                     email     Full_name
0   Tony   Stark         Ironman@gmail.com    Tony Stark
1  Steve  Rogers  CaptainAmerica@gmail.com  Steve Rogers

In [40]:
df3 = pd.concat([df,df2] ,ignore_index=True) # --> Concatinating the two dataframes (df and df2) in df3
display(df3)

    First     Last                     email       Full_name
0  convey  schafer    corveyscafer@gmail.com  convey schafer
1    John      Doe         Johndoe@gmail.com        John Doe
2    Jane      Doe         Janedoe@gmail.com        Jane Doe
3   Owais      Shk        owais123@gmail.com       Owais Shk
4    Tony    Stark         Ironman@gmail.com      Tony Stark
5   Steve   Rogers  CaptainAmerica@gmail.com    Steve Rogers

In [41]:
df.drop(index=0) # --> droping the row using index

   First Last               email  Full_name
1   John  Doe   Johndoe@gmail.com   John Doe
2   Jane  Doe   Janedoe@gmail.com   Jane Doe
3  Owais  Shk  owais123@gmail.com  Owais Shk

In [ ]:
df = df.drop(index = df[df['Last'] == "Doe"].index )  # --> deletes the person with last name "Doe"
display(df)

    First     Last                   email       Full_name
0  convey  schafer  corveyscafer@gmail.com  convey schafer
3   Owais      Shk      owais123@gmail.com       Owais Shk