# How to read csv files

In [28]:
import pandas as pd
df = pd.read_csv('ai_student_impact_dataset (1).csv')
display(df)

,Student_ID,Major_Category,...,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,...,86.44,High
1,100002,Medical,...,69.39,Low
2,100003,Business,...,73.93,Medium
3,100004,Business,...,63.58,Medium
4,100005,STEM,...,100.00,Medium
...,...,...,...,...,...
49995,149996,Business,...,66.16,High
49996,149997,STEM,...,81.62,Medium
49997,149998,Business,...,97.21,High
49998,149999,Business,...,84.12,Medium
49999,150000,Arts,...,76.16,Low

# Attributes to understand the data

In [ ]:
df.shape # --> gives info about the rows and columns only

(50000, 16)

In [ ]:
df.info() # --> gives info of rows and column as well as data types of the column

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  str
 2   Year_of_Study               50000 non-null  str
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  str
 6   Prompt_Engineering_Skill    50000 non-null  str
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  str
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  str
dtypes: bool(1), float64(5), int64(4), str(6)
memory usage: 5.8 MB

In [ ]:
pd.set_option('display.max_columns',4) # --> changes the setting of jupiter to display number of column we want to see!!

None

In [ ]:
df.head(10) # --> Gives fist 10 rows of the data

   Student_ID Major_Category  ... Skill_Retention_Score  Burnout_Risk_Level
0      100001     Humanities  ...                 86.44                High
1      100002        Medical  ...                 69.39                 Low
2      100003       Business  ...                 73.93              Medium
3      100004       Business  ...                 63.58              Medium
4      100005           STEM  ...                100.00              Medium
5      100006           STEM  ...                 65.92                High
6      100007           STEM  ...                 67.97              Medium
7      100008           Arts  ...                 85.09              Medium
8      100009       Business  ...                 55.71              Medium
9      100010       Business  ...                 87.18                High

[10 rows x 16 columns]

In [ ]:
df.tail(10) # --> Gives last 10 rows of the data

,Student_ID,Major_Category,...,Skill_Retention_Score,Burnout_Risk_Level
49990,149991,Business,...,84.87,Medium
49991,149992,Humanities,...,65.24,High
49992,149993,Business,...,84.04,Low
49993,149994,STEM,...,58.44,High
49994,149995,Humanities,...,74.76,High
49995,149996,Business,...,66.16,High
49996,149997,STEM,...,81.62,Medium
49997,149998,Business,...,97.21,High
49998,149999,Business,...,84.12,Medium
49999,150000,Arts,...,76.16,Low