# Basic Aggregate Function

In [9]:
import pandas as pd
df = pd.read_csv("ai_student_impact_dataset (1).csv", index_col='Student_ID')
df

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Student_ID,,,,,,,,,,,,,,,
100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [10]:
df['Pre_Semester_GPA'].median() # --> gives middle value of the dataset

np.float64(3.21)

In [11]:
df.describe() # --> gives broad statistical overview of the data

,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
count,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,3.146102,8.427752,2.80026,11.209271,3.505360,4.270760,3.349299,75.798125
std,0.478854,8.269490,1.18802,5.156426,1.820812,2.144066,0.495673,13.281626
min,1.183000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,10.780000
25%,2.834000,2.390000,2.00000,7.560000,2.000000,3.000000,3.023750,66.820000
50%,3.210000,5.800000,3.00000,11.180000,3.000000,4.000000,3.421000,76.000000
75%,3.521000,11.720000,4.00000,14.710000,5.000000,6.000000,3.749000,85.190000
max,3.998000,40.000000,5.00000,35.860000,10.000000,10.000000,4.000000,100.000000

In [12]:
df['Pre_Semester_GPA'].count() # --> gives count of Non-missing / non-NaN rows for specific column

np.int64(50000)

In [13]:
df['Major_Category'].value_counts()  # --> Tallies unique response in the column

Major_Category
STEM          15059
Business      12538
Humanities     9994
Medical        6476
Arts           5933
Name: count, dtype: int64

# Grouping the data

In [ ]:
major_group = df.groupby('Major_Category') # --> creating a group by specifying the column
major_group.get_group('Humanities') # --> getting the group according the values
display(major_group.get_group('Humanities').value_counts()) # --> applying function on the group

Major_Category  Year_of_Study  Pre_Semester_GPA  Weekly_GenAI_Hours  Primary_Use_Case          Prompt_Engineering_Skill  Tool_Diversity  Paid_Subscription  Traditional_Study_Hours  Perceived_AI_Dependency  Institutional_Policy   Anxiety_Level_During_Exams  Post_Semester_GPA  Skill_Retention_Score  Burnout_Risk_Level
Humanities      Senior         2.418             23.31               Copywriting/Drafting      Beginner                  1               True               8.13                     5                        Allowed_With_Citation  6                           2.393              86.44                  High                  1
                Sophomore      2.931             2.08                Direct_Answer_Generation  Advanced                  3               False              15.15                    5                        Strict_Ban             8                           3.214              59.69                  Medium                1
                Junior         2.975             0.51                Summarizing_Reading       Beginner                  1               False              10.84                    1                        Allowed_With_Citation  2                           3.412              53.95                  Medium                1
                Senior         3.579             0.45                Ideation                  Beginner                  1               True               10.61                    1                        Allowed_With_Citation  8                           3.760              55.33                  Low                   1
                Freshman       2.364             28.72               Copywriting/Drafting      Beginner                  1               False              8.24                     8                        Strict_Ban             7                           2.588              63.38                  Medium                1
                                                                                                                                                                                                                                                                                                                                ..
                Senior         2.540             8.05                Direct_Answer_Generation  Advanced                  4               False              14.73                    3                        Allowed_With_Citation  4                           3.029              100.00                 High                  1
                Sophomore      3.661             1.91                Copywriting/Drafting      Beginner                  3               True               14.19                    3                        Actively_Encouraged    2                           3.910              84.82                  Low                   1
                Junior         2.980             0.50                Direct_Answer_Generation  Intermediate              2               False              16.07                    4                        Allowed_With_Citation  2                           3.568              86.06                  Low                   1
                Freshman       2.708             13.34               Copywriting/Drafting      Intermediate              2               False              11.65                    4                        Allowed_With_Citation  5                           2.785              65.24                  High                  1
                Senior         3.556             15.19               Summarizing_Reading       Advanced                  4               True               1.00                     3                        Actively_Encouraged    5                           3.788              74.76                  High                  1
Name: count, Length: 9994, dtype: int64

# Advance grouping techniques

In [ ]:
import numpy as np 
df['Anxiety_Level_During_Exams'].agg([np.mean, np.median]) # --> use to run several function

mean      4.27076
median    4.00000
Name: Anxiety_Level_During_Exams, dtype: float64

In [ ]:
major_group['Major_Category'].apply(lambda x : x.str.contains('Humanities')).sum()

np.int64(9994)