# Sorting

In [37]:
import pandas as pd 
df = pd.read_csv("ai_student_impact_dataset (1).csv" , index_col="Student_ID")
df.head()

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Student_ID,,,,,,,,,,,,,,,
100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [38]:
df.sort_values(by='Post_Semester_GPA', ascending=False) # --> Basic Sorting

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Student_ID,,,,,,,,,,,,,,,
149980,Business,Senior,3.750,16.00,Ideation,Beginner,1,True,7.00,3,Allowed_With_Citation,1,4.000,66.12,Low
149977,Business,Graduate,3.692,7.31,Summarizing_Reading,Beginner,3,False,18.38,5,Actively_Encouraged,5,4.000,66.81,Medium
100030,STEM,Sophomore,3.638,12.83,Debugging/Troubleshooting,Advanced,4,True,10.25,5,Allowed_With_Citation,4,4.000,61.29,Medium
100026,Arts,Senior,3.308,2.38,Ideation,Advanced,4,True,11.33,2,Actively_Encouraged,2,4.000,81.85,High
149951,Humanities,Freshman,3.848,3.64,Copywriting/Drafting,Intermediate,4,False,12.23,1,Allowed_With_Citation,4,4.000,79.59,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111361,Arts,Freshman,1.408,1.58,Direct_Answer_Generation,Intermediate,2,False,4.42,2,Actively_Encouraged,5,1.316,68.63,Low
139394,Medical,Junior,1.703,24.47,Direct_Answer_Generation,Beginner,3,False,3.33,4,Allowed_With_Citation,6,1.226,53.30,High
110885,Business,Freshman,1.183,12.83,Summarizing_Reading,Beginner,3,False,13.21,5,Allowed_With_Citation,8,1.209,81.87,High
143352,Humanities,Junior,1.346,7.22,Copywriting/Drafting,Beginner,1,False,2.18,2,Strict_Ban,3,1.190,59.03,Medium
118079,STEM,Junior,1.431,40.00,Direct_Answer_Generation,Beginner,1,True,8.95,9,Strict_Ban,9,1.000,10.78,High

In [ ]:
df.sort_values(by=['Pre_Semester_GPA','Post_Semester_GPA'], ascending=[False,False]) # --> Multiple sorting

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Student_ID,,,,,,,,,,,,,,,
116143,Medical,Junior,3.998,10.63,Summarizing_Reading,Advanced,4,False,17.40,6,Strict_Ban,7,4.000,100.00,Medium
100644,Humanities,Senior,3.997,0.47,Ideation,Beginner,1,False,3.18,5,Actively_Encouraged,2,4.000,66.05,Low
109477,Medical,Sophomore,3.994,17.75,Summarizing_Reading,Beginner,3,False,16.35,6,Actively_Encouraged,4,4.000,90.42,Medium
129440,Humanities,Junior,3.993,2.01,Copywriting/Drafting,Advanced,3,True,11.45,3,Strict_Ban,2,4.000,90.38,Low
103869,Business,Sophomore,3.992,3.78,Summarizing_Reading,Advanced,3,True,11.16,1,Strict_Ban,1,3.966,81.24,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145587,Medical,Graduate,1.317,4.25,Summarizing_Reading,Beginner,3,False,18.89,2,Actively_Encouraged,6,1.640,51.97,Medium
147145,STEM,Junior,1.294,5.43,Ideation,Advanced,5,False,19.86,1,Strict_Ban,6,1.740,75.83,Medium
107056,STEM,Senior,1.292,6.65,Debugging/Troubleshooting,Beginner,1,False,14.36,4,Strict_Ban,4,1.524,85.71,Medium
145426,STEM,Sophomore,1.275,7.01,Ideation,Intermediate,1,True,2.58,6,Allowed_With_Citation,6,1.366,91.98,Low
110885,Business,Freshman,1.183,12.83,Summarizing_Reading,Beginner,3,False,13.21,5,Allowed_With_Citation,8,1.209,81.87,High

In [ ]:
df.sort_index(ascending=False) # --> Sorting the index

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Student_ID,,,,,,,,,,,,,,,
150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low
149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High

In [ ]:
df['Anxiety_Level_During_Exams'].nlargest(1000).tail() # --> Sorting largest values in series

Student_ID
116906    9
116949    9
117089    9
117134    9
117143    9
Name: Anxiety_Level_During_Exams, dtype: int64

In [ ]:
df.nlargest(10,'Perceived_AI_Dependency').tail(10) # --> Sorting on Dataframe

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Student_ID,,,,,,,,,,,,,,,
100125,STEM,Sophomore,3.446,40.00,Summarizing_Reading,Intermediate,4,False,7.47,10,Actively_Encouraged,2,3.441,76.67,High
100557,STEM,Senior,2.741,40.00,Debugging/Troubleshooting,Beginner,3,True,12.49,10,Allowed_With_Citation,8,3.095,70.23,High
100651,STEM,Senior,3.428,39.00,Direct_Answer_Generation,Beginner,1,False,13.44,10,Actively_Encouraged,7,2.902,39.14,High
100657,STEM,Senior,3.169,40.00,Ideation,Beginner,1,False,10.78,10,Strict_Ban,10,3.420,78.48,High
101341,STEM,Graduate,3.315,34.11,Copywriting/Drafting,Beginner,3,False,16.45,10,Allowed_With_Citation,10,3.488,59.17,High
101795,STEM,Freshman,3.301,40.00,Debugging/Troubleshooting,Intermediate,3,True,5.61,10,Allowed_With_Citation,7,3.183,52.77,High
102012,STEM,Freshman,3.516,40.00,Debugging/Troubleshooting,Beginner,3,False,6.29,10,Allowed_With_Citation,6,3.689,54.38,High
102189,Arts,Freshman,3.503,36.00,Direct_Answer_Generation,Intermediate,2,False,9.19,10,Actively_Encouraged,7,3.287,64.11,High
103212,Business,Graduate,2.336,38.26,Summarizing_Reading,Beginner,2,True,8.70,10,Actively_Encouraged,4,2.540,60.50,Medium
103801,STEM,Sophomore,3.604,40.00,Summarizing_Reading,Advanced,4,True,9.04,10,Allowed_With_Citation,4,4.000,61.51,High